--Q1. Total Revenue generated by male vs Female Customers
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--Q2. Customers used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--Q3. Top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;

--Q4. Comparing the average Purchase Amounts between Standard and Express Shipping
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5. Do Susbscribed customers spend more? Compare average spend amount and total
--revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT (customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM (purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

--Q6. 5 Products with highest percentage of purchases with discounts applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;

--Q7. Segment Customers into New, Returning, and Loyal based on their total 
--number of previous purchases, and the count of each segment
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
   WHEN previous_purchases = 1 THEN 'New'
   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
   FROM customer
   )

   SELECT customer_segment, count(*) as "Number of Customers"
   FROM customer_type
   GROUP BY customer_segment;

--Q8. Top 3 most purchased products within each category
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are Customers who are repeat buyer (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS REPEAT_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. Revenue contribution of each group
SELECT age_group,
SUM(purchase_amount) as Total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
